spring.application.name=hngpractise
server.port=${PORT:8080}

# Railway Database Connection
spring.datasource.url=jdbc:mysql://nozomi.proxy.rlwy.net:39253/railway
spring.datasource.username=root
spring.datasource.password=ctDokvCslmYWVPtSjycXfKodiLjkymeQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# GitHub OAuth Credentials
spring.security.oauth2.client.registration.github.client-id=Ov23libTKVOGGXySyEwe
spring.security.oauth2.client.registration.github.client-secret=d29c06531f1da2588eec8f0ef5c518e087c0c7cc

# JWT Configuration (Required for our JwtService)
jwt.secret=insighta_labs_plus_secure_backend_key_2024_stage_3
